oop homework
Valentyna777/common pull request #15
Opened 2019-10-18 06:23 UTC by Valentyna777

2019-10-22 16:58 UTC, pavlozubariev requested changes

2019-10-22 16:58 UTC, pavlozub85 commented on oop/homework.py
> +            self._increase_saturation_level(2)
якщо продуктів буде більше то буде не практично писати багато if ... elif, спробуй покращити і можна ще додати перевірку для випадку коли у функцію передають продукт якого немає в переліку

2019-10-22 16:58 UTC, pavlozub85 commented on oop/homework.py
> +            self._increase_saturation_level(15)
аналогічно як і в класі Cat

2019-10-22 16:58 UTC, pavlozub85 commented on oop/homework.py
> +        self.average_speed = self._set_average_speed()
навіщо average_speed = None і чому saturation_level = 50 вказано за межами методу __init__?

2019-10-22 16:58 UTC, pavlozub85 commented on oop/homework.py
> +        return self.average_speed
self.average_speed не потрібно призначати всередині методу _set_average_speed
потрібно в методі _set_average_speed за вчідним параметром повернути значення яке потім буде записано в атрибут self.average_speed. в батьківському класі Cat написано правильно, почитай про успадкування класів (inheritance)

2019-10-22 16:58 UTC, pavlozub85 commented on oop/homework.py
> +    metal_price = 3
wood_price і metal_price не в методі init?

2019-10-22 16:58 UTC, pavlozub85 commented on oop/homework.py
> +        pass
чому атрибути не в методі init?

2019-10-22 19:09 UTC, Valentyna777 commented on oop/homework.py
> +            self._increase_saturation_level(2)
Зробила а допомогою словника. Додала варіант для випадку коли у функцію передають продукт якого немає

2019-10-22 19:10 UTC, Valentyna777 commented on oop/homework.py
> +            self._increase_saturation_level(15)
зробила аналогічно

2019-10-22 19:10 UTC, Valentyna777 commented on oop/homework.py
> +        self.average_speed = self._set_average_speed()
Здалося, що так казав Денис на практичному завданні, мабуть, неправильно зрозуміла. Виправила.

2019-10-22 19:12 UTC, Valentyna777 commented on oop/homework.py
> +        return self.average_speed
В батьківському класі було виправлено згідно зауваження після перевірки одногрупником, тут виправити забула. Вже зробила.

2019-10-22 19:12 UTC, Valentyna777 commented on oop/homework.py
> +    metal_price = 3
Додала в метод.

2019-10-22 19:12 UTC, Valentyna777 commented on oop/homework.py
> +        pass
Також додала до методу.

2019-10-23 18:14 UTC, pavlozubariev approved these changes

2019-10-28 18:03 UTC, merged